### ISSUE TITLE
listchannels not displaying correctly

### ISSUE THREAD

**Issue by bb2k16** [bitromortac/lndmanage#35]
when I tired the `listchannels` command, the output was like this:

![image](https://user-images.githubusercontent.com/22429074/62074596-06e50e00-b23b-11e9-88c4-62d821b5ba1a.png)

similiar issue with other command, such as `recommend-nodes`

![image](https://user-images.githubusercontent.com/22429074/62074814-7824c100-b23b-11e9-9eca-3033b946663d.png)

Windows 10, python 3.7.4

**Comment by bitromortac** [comment]
Thank you for reporting! This seems to be an encoding issue maybe with powershell. I'm developing on Linux and didn't encounter this so far. Will test it on Windows and let you know!

**Comment by lukeroberts** [comment]
Having this issue on Windows server 2019 as well in both powershell and cmd

**Comment by bitromortac** [comment]
I am currently focusing on building a test integration for lndmanage, which should be finished by the end of this week. Afterwards this will have top priority.

**Comment by bitromortac** [comment]
Could reproduce this in powershell and mingw64 shells. The problem is that `sys.stdout.encoding` is set to `cp1252` instead of `utf8`. The `cp1252` charset (https://en.wikipedia.org/wiki/Windows-1252) doesn't support unicode characters as are used in the lightning network aliases.
Will investigate what I can do about it.

**Comment by bitromortac** [comment]
Could you try f4ebf64d4da33c9024fca347838d3153679453a5? This fixes the encoding when writing to log files in utf-8 encoding.

Additionally there's the problem of encoding of standard output in the shell you are using. In powershell try `set PYTHONIOENCODING='utf-8'` before running lndmanage (http://www.tiernok.com/posts/python-3-6-unicode-output-for-windows-console.html). You can also make this permanent in your system environment variables (https://www.techjunkie.com/environment-variables-windows-10/).

Note: Some characters still may not be well represented in your output, but that is due to the font not supporting utf-8 characters. You can also try to have a look at lndmanage.log, which is created after running.

**Comment by lukeroberts** [comment]
For powershell it seems to want it set this way: ```$env:PYTHONIOENCODING="UTF-8"```

But after the latest commit and using that command everything seems to work. Thanks!

**Comment by bitromortac** [comment]
Perfect, thanks for the feedback. I put some installation notes for windows into the readme (a0d71ce789156e7e5c763c3c4cb1d91be6abc82a).
