### ISSUE TITLE
Error in annotations = config['annotations']

### ISSUE THREAD

**Issue by openoms** [bitromortac/lndmanage#40]
While running: 
`(lndmanage) admin@RPi4:~/lndmanage $ ./lndmanage.py listchannels rebalance`
```
Initializing node interface.
Initializing network graph.
Saved graph is too old. Fetching new one.
Traceback (most recent call last):
  File "./lndmanage.py", line 365, in <module>
    main()
  File "./lndmanage.py", line 289, in main
    args.unbalancedness, sort_string=args.sort_by)
  File "/home/admin/lndmanage/lib/listchannels.py", line 313, in print_channels_unbalanced
    self.node.get_unbalanced_channels(unbalancedness))
  File "/home/admin/lndmanage/lib/listchannels.py", line 396, in _add_channel_annotations
    annotations = config['annotations']
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'annotations'
```
`$ ./lndmanage.py status` and 
`$ ./lndmanage.py rebalance` works as expected. Getting the channel ID-s from RTL.

**Comment by bitromortac** [comment]
That's due to the removal of the file 'channel_annotations' from the project, which is now in a section of the config.ini file.

If you use latest master, then old config.ini files are currently incompatible because of the missing `[annotations]` section (compare with `config_sample.ini`).

I'll make this pass even if no such definition is present.

**Comment by openoms** [comment]
Thank you for the quick response. 
Adding
`[annotations]`
to the `config.ini` has solved the problem.
